spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/garage?useTimezone=true&serverTimezone=UTC
    username: garage
    password: 'G@rAg3Inc'
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      poolName: Garage
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    servlet:
      load-on-startup: -1
  jersey:
    servlet:
      load-on-startup: 1
  http:
    enconding:
      force: true
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      write_dates_as_timestamps: false

server:
  use-forward-headers: true

garage:
  web:
    authentication:
      jwt:
        secret-key: "G@rAg3Inc"
        expiration: 43200000
      request-filter:
        prefix: "Bearer "
        header: "Authorization"
